sonar.projectKey=Joyanta1234_mark
sonar.organization=joyanta1234
sonar.projectName=mark
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=node_modules/**,dist/**,docs/**,public/**,coverage/**,*.config.js,*.config.ts,postcss.config.js,tailwind.config.js,vite.config.ts
sonar.test.exclusions=node_modules/**,dist/**,docs/**,public/**
